#!/usr/bin/perl -w

=head1 NAME

dh_makegolangshlibs - Generates golang-specific shlibs files and substvars

=cut

use strict;
use Debian::Debhelper::Dh_Lib;
use File::Find;
use JSON;
use MIME::Base64;

=head1 SYNOPSIS

B<dh_makegolangshlibs> [S<I<debhelper options>>]

=head1 DESCRIPTION

B<dh_makegolangshlibs> is a debhelper program which generates a
substvar and shlibs file to enable packages depending on go shared
libraries to conveniently depend on the ABI hash of the library rather
than just the soversion.  It replaces dh_makeshlibs in the usual dh
sequences.

=head1 NOTES

The best way to invoke B<dh_makegolangshlibs> is by using B<dh --with=golang>.

=cut

init();

############################################################################
# Generate ...
############################################################################

my ($libpkg, $devpkg);

foreach my $pkg (@{$dh{DOPACKAGES}}) {
    if ($pkg =~ /^lib.*[0-9]$/) {
        $libpkg = $pkg;
    }
    if ($pkg =~ /-dev$/) {
        $devpkg = $pkg;
    }
}

if (!defined($libpkg)) {
    exit(0);
} elsif (!defined($devpkg)) {
    printf("found lib package but not dev");
    exit(1);
}

my $devpkgdir = tmpdir($libpkg);
my @sofiles;
find({
    wanted => sub {
        my $F = $File::Find::name;

        if ($F =~ /.so.[0-9]+$/ ) {
            push @sofiles, $F;
        }
    },
    no_chdir => 1,
     } ,$devpkgdir);
if (@sofiles != 1) { die "too many / too few"; }

my $hexhash=`/usr/lib/go/readabihash @sofiles`;
chomp($hexhash);

my $libpkgdir=tmpdir($libpkg);
my ($libname, $sover) = ($libpkg =~ /^lib(.*?)-?([0-9]+)$/);

if (! -d "$libpkgdir/DEBIAN") {
    doit("install","-d","$libpkgdir/DEBIAN");
}
my $provides = "$libpkg-$hexhash";
addsubstvar($libpkg, "golang:Provides", $provides);
complex_doit("echo 'lib$libname $sover $provides' >>$libpkgdir/DEBIAN/shlibs");
autoscript($libpkg,"postinst","postinst-makeshlibs");
autoscript($libpkg,"postrm","postrm-makeshlibs");


=head1 SEE ALSO

dh(1)

=head1 AUTHORS

Michael Hudson-Doyle <michael.hudson@canonical.com>

=cut

# vim:ts=4:sw=4:et
